// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm5slqnNAlbvM8MVG5GNsQeyuf6OFkVcE',
    appId: '1:412397077350:web:26907c85a5d7e0ce1b3ea7',
    messagingSenderId: '412397077350',
    projectId: 'login-with-getx-c580a',
    authDomain: 'login-with-getx-c580a.firebaseapp.com',
    storageBucket: 'login-with-getx-c580a.firebasestorage.app',
    measurementId: 'G-SG3TWQF6VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUa9nQUqlQjIW377O7IxHbT8ShMnAOka4',
    appId: '1:412397077350:android:dbcd164d878578e91b3ea7',
    messagingSenderId: '412397077350',
    projectId: 'login-with-getx-c580a',
    storageBucket: 'login-with-getx-c580a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjRyISGZ97WkB5bC5UV_VCvL91gQQm9yk',
    appId: '1:412397077350:ios:7d7bd00616f8415a1b3ea7',
    messagingSenderId: '412397077350',
    projectId: 'login-with-getx-c580a',
    storageBucket: 'login-with-getx-c580a.firebasestorage.app',
    iosBundleId: 'com.example.loginApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjRyISGZ97WkB5bC5UV_VCvL91gQQm9yk',
    appId: '1:412397077350:ios:7d7bd00616f8415a1b3ea7',
    messagingSenderId: '412397077350',
    projectId: 'login-with-getx-c580a',
    storageBucket: 'login-with-getx-c580a.firebasestorage.app',
    iosBundleId: 'com.example.loginApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm5slqnNAlbvM8MVG5GNsQeyuf6OFkVcE',
    appId: '1:412397077350:web:5a0cccb6a21e796b1b3ea7',
    messagingSenderId: '412397077350',
    projectId: 'login-with-getx-c580a',
    authDomain: 'login-with-getx-c580a.firebaseapp.com',
    storageBucket: 'login-with-getx-c580a.firebasestorage.app',
    measurementId: 'G-94DLPHY01Q',
  );
}
